"""orden de compra 

Revision ID: 18cfe1051e29
Revises: b82bec9ae94a
Create Date: 2024-05-12 00:51:14.188212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cfe1051e29'
down_revision: Union[str, None] = 'b82bec9ae94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade()-> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden_compra', sa.Column('Producto', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('orden_compra_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'orden_compra', ['orden_compra_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'orden_compra_id')
    op.drop_column('orden_compra', 'Producto')
    # ### end Alembic commands ###
